### ISSUE TITLE
Any plans to make this support Rails 5?

### ISSUE THREAD

**Issue by patricklindsay** [tknarr/before_render#1]
I could have a look if not.. @tknarr ?

**Comment by tknarr** [comment]
Yes, in fact there's a branch for it already (rails5_compatibility_2). I haven't figured out the problem with the tests, though, the code appears to work and matches what should work but fails the test and I'm not sure if it's a problem with the code or a fault in the test itself.

**Comment by patricklindsay** [comment]
Ah yes thanks I found that just after asking. 

I spent a couple hours trying to fix those tests but had no joy. I think it's a problem with the code though rather than the tests as the action which is passed in is no longer being carried out.. just can't see why it wouldn't work.  :(

As a workaround for now I'm doing this;

```

    # Override added as workaround for before_render Rails 5 incompatibility
    def render(*args, &blk)
      before_render
      super
    end

    # Actions that should be carried out before rendering
    def before_render
      load_meta_tags
    end
```

**Comment by tknarr** [comment]
It's getting into run_callbacks, and the proper callback looks like it's in the chain, but somewhere while running the chain it never gets run. I'm working on debugging it.

**Comment by tknarr** [comment]
Found it. It's an issue in the test itself. Both before_render and prepend_before_render on the test controller were referring to the same action. That seems to have messed up the condition evaluation and made ActiveSupport::Callbacks think the condition had failed and the callback wasn't to be run. Changed things so the two referred to different methods and things work as expected.

**Comment by tknarr** [comment]
Will be merging to master.
